timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/standard-1.maude > ./results/standard-1.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/standard-2.maude > ./results/standard-2.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/standard-3.maude > ./results/standard-3.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/canonical-1.maude > ./results/canonical-1.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/canonical-2.maude > ./results/canonical-2.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/canonical-3.maude > ./results/canonical-3.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/filtered-1.maude > ./results/filtered-1.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/filtered-2.maude > ./results/filtered-2.txt & disown
timeout 36000 maude ./../conditional-narrowing.maude ./ft-channel.maude ./tests/filtered-3.maude > ./results/filtered-3.txt & disown
